### ISSUE TITLE
is there a solution?

### ISSUE THREAD

**Issue by DWLinden** [AdamCSmithCWS/JAGS-version-compare#1]
Hi Adam,

Very happy to have found your reply on Martyn Plummers blog, and the testing you did here.  It seems you may have found a solution to this problem?

I recently upgraded JAGS to 4.3 (after a complete R upgrade) and started having trouble fitting old model structures that previously worked.  Models never got past initializing.  I've reverted back to 4.2 as a short term solution.  But honestly, I'm surprised more people have not had this issue and chirped about it since the release of 4.3 almost 3 years ago.  I have 2 Windows laptops and 1 Linux (Ubuntu), all with the problem after upgrading.

Any insights would be appreciated!

Thanks,
Dan

**Comment by AdamCSmithCWS** [comment]
Thanks @danlinden . I'm sorry I didn't notice your issue back in the spring. I've added a band-aid solution - don't load the glm module. It now works with JAGS 4.3.
It's an imperfect solution thought, because the glm module is otherwise a very helpful package of samplers.

My long-term solution, is to transition to using Stan and Nimble (sigh).
